import json
from pathlib import Path

import pytest

pytest_plugins = "pytest_homeassistant_custom_component"

STATUS = json.loads((Path(__file__).parent / "fixtures" / "status.json").read_text())


@pytest.fixture(autouse=True)
def auto_enable_custom_integrations(enable_custom_integrations):
    """Let Home Assistant load custom_components/ in these tests."""
    yield


@pytest.fixture
def status():
    """A copy of a realistic /status.json (generated by the watcher's own status builder)."""
    return json.loads(json.dumps(STATUS))
