import json
from pathlib import Path

import pytest

pytest_plugins = "pytest_homeassistant_custom_component"

STATUS = json.loads((Path(__file__).parent / "fixtures" / "status.json").read_text())


@pytest.fixture(autouse=True)
def auto_enable_custom_integrations(enable_custom_integrations):
    """Let Home Assistant load custom_components/ in these tests."""
    yield


@pytest.fixture
def status():
    """A copy of a realistic /status.json (generated by the watcher's own status builder)."""
    return json.loads(json.dumps(STATUS))


HOST, PORT, TOKEN = "10.0.0.5", 8099, "tok-0123456789abcdef"
BASE = f"http://{HOST}:{PORT}"
WATCHES = [
    {"name": "Out: Sydney to Shanghai/Hangzhou", "from": ["SYD"], "to": ["PVG", "HGH"],
     "start": "2027-05-10", "end": "2027-05-20"},
    {"name": "Back: Shanghai/Hangzhou to Sydney", "from": ["PVG", "HGH"], "to": ["SYD"],
     "start": "2027-05-17", "end": "2027-05-30"},
]


def view(source="config.toml", editable=True, watches=None):
    watches = WATCHES if watches is None else watches
    return {"source": source, "editable": editable, "watches": watches, "combos": 50,
            "limits": {"max_watches": 20, "max_airports": 10, "max_window_days": 120, "max_combos": 400}}


def mock_watcher(aioclient_mock, status, put=(200, None), **view_kw):
    """Registers every endpoint of a healthy, editable watcher. `put` = (status, json) overrides
    the answer to PUT /config (the mock uses the first matching route, so it must be set here)."""
    aioclient_mock.get(f"{BASE}/status.json", json=status)
    aioclient_mock.get(f"{BASE}/config", json=view(**view_kw))
    aioclient_mock.get(f"{BASE}/auth", json={"ok": True})
    put_status, put_json = put
    aioclient_mock.put(f"{BASE}/config", status=put_status,
                       json=put_json or view(source="home-assistant", **{k: v for k, v in view_kw.items() if k != "source"}))
    aioclient_mock.delete(f"{BASE}/config", json=view())


def calls(aioclient_mock, method):
    """[(path, json body, Authorization header)] of the requests made with this method."""
    return [(str(url.path), data, (headers or {}).get("Authorization"))
            for m, url, data, headers in aioclient_mock.mock_calls if m == method]
